# -*- coding: utf-8 -*-
"""clase1-corte2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifEeA6yn-gEpxwrzBJdeWtoQWUd7NIR0
"""

#ejercicio grupos
"""
Integrantes:
- Junior Reyes
- Johan Sebastian Beleño Toloza
"""

"""
1. Escriba una función en python que pida un número entero positivo y que cree un diccionario cuyas claves sean desde el número 1 hasta el número indicado, y los valores sean los cuadrados de las claves.
2. Escribe una función que reciba como parámetro una cadena y devuelva un diccionario con la cantidad de apariciones de cada carácter en la cadena.
3. Crear un programa en python donde se va a declarar un diccionario para guardar los precios de distintas frutas. El programa pedirá el nombre de la fruta y la cantidad que se ha vendido y mostrará el precio final de la fruta a partir de los datos guardados en el diccionario. Si la fruta no existe nos dará un error. Tras cada consulta el programa nos preguntará si queremos hacer otra consulta.
"""


#ejercicio 1
n_ped=int(input("ingrese un numero entero positivo: "))
diccionario={}
for i in range(1,n_ped+1):
  diccionario[i]=i**2
print(diccionario)

#2 = Escribe una función que reciba como parámetro una cadena y devuelva un diccionario con la cantidad de apariciones de cada carácter en la cadena.
def contar_caracteres(cadena):
    diccionario = {}
    for caracter in cadena:
        if caracter in diccionario:
            diccionario[caracter] += 1
        else:
            diccionario[caracter] = 1
    return diccionario

print(contar_caracteres("hola mundo"))

#ejercicio 3
precios = {"manzana": 4000, "pera": 2000, "uva": 1000, "fresa": 3000}
while True:
   fruta = input("Ingrese el nombre de la fruta de la fruta: ").lower()
   if fruta in precios:
      cantidad = float(input("Ingrese la cantidad de la fruta vendida: "))
      total = precios[fruta] * cantidad
      print(f"El precio total de: ${total}")
   else:
       print("error: esa fruta no existe")

   otra = input("quieres hacer otra consulta? (si/no): ")
   if otra.lower() !='si':
      break
