# -*- coding: utf-8 -*-
"""clase1-corte2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifEeA6yn-gEpxwrzBJdeWtoQWUd7NIR0
"""

#Diccionerips
diccionario={'nombre':'Carlos','edad':22,'cursos':['Python','Django','JavaScript']}
print(diccionario['nombre'])#carlos
print(diccionario['edad'])#22
print (diccionario['cursos'])#['Python','Django','JavaScript']

#mapeo de users
dicc_user_ed={
    "Lau":28,
    "dani":31,
    "Alber":27,
    "Rogelio":65

}
print("Diccionario edades de users: ",dicc_user_ed)
print("-------------------------------------")
#generar una oracion para cada usuario
for usuario,edad in dicc_user_ed.items():
    print(f"El usuario {usuario} tiene {edad} años")

#acceder a los valores de 2 users especificos
print("-------------------------------------")
user1="Lau"
user2="Alber"
print(f"El usuario {user1} tiene {dicc_user_ed[user1]} años")
print(f"El usuario {user2} tiene {dicc_user_ed[user2]} años")

print("-------------------------------------")
#cambiar la edad de rogelio a 35

dicc_user_ed["Rogelio"]=35
print("Nuevo diccionario de users y edades",dicc_user_ed)


#agregar a eva al diccionario
print("-------------------------------------")
dicc_user_ed["Eva"]=29
print("Nuevo diccionario de users y edades",dicc_user_ed)

#borrar a dani al diccionario
print("-------------------------------------")
del dicc_user_ed["dani"]
print("Nuevo diccionario de users y edades",dicc_user_ed)

print("-------------------------------------")
#buscaar a alguien que no estaá en un diccionario (pepe)
print(dicc_user_ed.get("pepe","No esta en el diccionario"))

print("-------------------------------------")
#obtener la edad de un user
edad_eva=dicc_user_ed["Eva"]
print(f"La edad de Eva es {edad_eva}")


# obtener la edad de pepe con valor predeterminado de -1 si no está en el diccionario
print("-------------------------------------")
edad_pepe=dicc_user_ed.get("Pepe",-1)
if edad_pepe!=-1:
    print(f"La edad de Pepe es {edad_pepe}")
else:
    print("Pepe no está en el diccionario")

#verificar si pepe y eva están
print("-------------------------------------")

if "Pepe" in dicc_user_ed:
    print("Pepe está en el diccionario")
else:
    print("Pepe no está en el diccionario")

#verificar du Eva está en el diccionaerio
if "Eva" in dicc_user_ed:
    print("Eva está en el diccionario")
else:
    print("Eva no está en el diccionario")

print("-------------------------------------")

#ejercicio grupos
"""
Integrantes:
- Junior Reyes
- Johan Sebastian Beleño Toloza
"""

"""
1. Escriba una función en python que pida un número entero positivo y que cree un diccionario cuyas claves sean desde el número 1 hasta el número indicado, y los valores sean los cuadrados de las claves.
2. Escribe una función que reciba como parámetro una cadena y devuelva un diccionario con la cantidad de apariciones de cada carácter en la cadena.
3. Crear un programa en python donde se va a declarar un diccionario para guardar los precios de distintas frutas. El programa pedirá el nombre de la fruta y la cantidad que se ha vendido y mostrará el precio final de la fruta a partir de los datos guardados en el diccionario. Si la fruta no existe nos dará un error. Tras cada consulta el programa nos preguntará si queremos hacer otra consulta.
"""


#ejercicio 1
n_ped=int(input("ingrese un numero entero positivo: "))
diccionario={}
for i in range(1,n_ped+1):
  diccionario[i]=i**2
print(diccionario)

#2 = Escribe una función que reciba como parámetro una cadena y devuelva un diccionario con la cantidad de apariciones de cada carácter en la cadena.
def contar_caracteres(cadena):
    diccionario = {}
    for caracter in cadena:
        if caracter in diccionario:
            diccionario[caracter] += 1
        else:
            diccionario[caracter] = 1
    return diccionario

print(contar_caracteres("hola mundo"))

#ejercicio 3
precios = {"manzana": 4000, "pera": 2000, "uva": 1000, "fresa": 3000}
while True:
   fruta = input("Ingrese el nombre de la fruta de la fruta: ").lower()
   if fruta in precios:
      cantidad = float(input("Ingrese la cantidad de la fruta vendida: "))
      total = precios[fruta] * cantidad
      print(f"El precio total de: ${total}")
   else:
       print("error: esa fruta no existe")

   otra = input("quieres hacer otra consulta? (si/no): ")
   if otra.lower() !='si':
      break